/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE teacherBaseService PLEASE EDIT ../teacher.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Teacher } from '../../domain/schoolmanager_db/teacher';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../teacher.service.ts
 */

/*
 * SCHEMA DB teacher
 *
	{
		lastname: {
			type: 'String',
			required : true
		},
		name: {
			type: 'String',
			required : true
		},
		phone: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
	}
 *
 */
@Injectable()
export class TeacherBaseService {

    contextUrl: string = environment.endpoint + '/teacher';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * teacherService.create
    *   @description CRUD ACTION create
    *   @param teacher obj Object to insert
    *
    */
    create(item: Teacher): Observable<Teacher> {
        return this.http
            .post<Teacher>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * teacherService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id teacher
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * teacherService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id teacher
    *   @returns teacher
    *
    */
    get(id: string): Observable<Teacher> {
        return this.http
            .get<Teacher>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * teacherService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id teacher
    *   @returns teacher
    *
    */
    update(item: Teacher): Observable<Teacher> {
        return this.http
            .post<Teacher>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
